services:
  - type: web
    name: class-match-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: class-match-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: "4"

databases:
  - name: class-match-db
    plan: free